# Generated by Django 2.2.19 on 2022-09-12 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='description',
        ),
    ]
