# Generated by Django 2.2.19 on 2022-09-15 19:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='attorney',
            name='test',
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='test',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contracts.Attorney', to_field='test'),
        ),
    ]
